from django.urls import path
from web import views

#app_name="web"


urlpatterns=[
    path('rupesh',views.rupesh,name='rupesh'),
    path('Teams',views.Teams,name='Teams'),
    path('players',views.Players,name='Players'),
    path('Rankings',views.Rankings,name='Rankings'),
    path('Stats',views.Stats,name='Stats'),
    path('Records',views.Records,name='Records'),
    path('IPL',views.IPL,name='IPL'),
    path('all',views.all,name='all'),
    path('india',views.india,name='india'),
    path('australia',views.australia,name='australia'),
    path('southafrica',views.southafrica,name='southafrica'),
    path('westindies',views.westindies,name='westindies'),
    path('england',views.england,name='england'),
    path('newzland',views.newzland,name='newzland'),
    path('srilanka',views.srilanka,name='srilanka'),
    path('irland',views.irland,name='irland'),
    path('pak',views.pak,name='pak'),
    path('afgan',views.afgan,name='afgan'),
    path('zimbawe',views.zimbawe,name='zimbawe'),
    path('bangaladesh',views.bangaladesh,name='bangaladesh'),
    path('batting',views.batting,name='batting'),
    path('bowling',views.bowling,name='bowling'),
    path('test',views.test,name='test'),
    path('odi',views.odi,name='odi'),
    path('twinty',views.twinty,name='twinty'),
    path('testbowling',views.hit,name='testbowling'),
    path('odibowling',views.wicket,name='odibowling'),
    path('twintybowling',views.stumps,name='twintybowling'),
    #path('dhoni',views.dhoni,name='dhoni'),
    path('icc_test',views.icc_test,name='icc_test'),
    path('icc_odi',views.icc_odi,name='icc_odi'),
    path('icct20',views.icct20,name='icct20'),
    path('icc_test_team',views.icc_test_team,name='icc_test_team'),
    path('icc_testbatting_team',views.icc_testbatting_team,name='icc_testbatting_team'),
    path('icc_testbowling_team',views.icc_testbowling_team,name='icc_testbowling_team'),
    path('icc_testallrounder_team',views.icc_testallrounder_team,name='icc_testallrounder_team'),
    path('icc_odi_team',views.icc_odi_team,name='icc_odi_team'),
    path('icc_odibatting_team',views.icc_odibatting_team,name='icc_odibatting_team'),
    path('icc_odibowling_team',views.icc_odibowling_team,name='icc_odibowling_team'),
    path('icc_odiallrounder_team',views.icc_odiallrounder_team,name='icc_odiallrounder_team'),
    path('icc_t20_team',views.icc_t20_team,name='icc_t20_team'),
    path('icc_t20batting_team',views.icc_t20batting_team,name='icc_t20batting_team'),
    path('icc_t20bowling_team',views.icc_t20bowling_team,name='icc_t20bowling_team'),
    path('icc_t20allrounder_team',views.icc_t20allrounder_team,name='icc_t20allrounder_team'),
]
