# Generated by Django 3.2.6 on 2021-10-05 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testruns',
            name='country',
            field=models.CharField(max_length=100),
        ),
    ]
