# Generated by Django 3.2.6 on 2021-10-06 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_alter_testruns_country'),
    ]

    operations = [
        migrations.CreateModel(
            name='Format',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, unique=True)),
                ('country', models.CharField(max_length=100)),
                ('matches', models.IntegerField()),
                ('wickets', models.IntegerField()),
                ('econamy', models.DecimalField(decimal_places=2, max_digits=3)),
            ],
        ),
        migrations.CreateModel(
            name='Odibal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, unique=True)),
                ('country', models.CharField(max_length=100)),
                ('matches', models.IntegerField()),
                ('wickets', models.IntegerField()),
                ('econamy', models.DecimalField(decimal_places=2, max_digits=3)),
            ],
        ),
        migrations.CreateModel(
            name='Odiruns',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, unique=True)),
                ('country', models.CharField(max_length=100)),
                ('runs_scored', models.IntegerField()),
                ('high_score', models.IntegerField()),
                ('hundreds', models.IntegerField()),
                ('fifties', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Testbal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, unique=True)),
                ('country', models.CharField(max_length=100)),
                ('matches', models.IntegerField()),
                ('wickets', models.IntegerField()),
                ('econamy', models.DecimalField(decimal_places=2, max_digits=3)),
            ],
        ),
        migrations.CreateModel(
            name='Truns',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, unique=True)),
                ('country', models.CharField(max_length=100)),
                ('matches', models.IntegerField()),
                ('runs_scored', models.IntegerField()),
                ('high_score', models.IntegerField()),
                ('hundreds', models.IntegerField()),
                ('fifties', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='testruns',
            name='high_score',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='testruns',
            name='matches',
            field=models.IntegerField(null=True),
        ),
    ]
