# Generated by Django 3.2.6 on 2021-10-12 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0005_alter_comment_body'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestRankings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rank', models.IntegerField()),
                ('player', models.CharField(max_length=80)),
                ('country', models.CharField(max_length=80)),
                ('points', models.IntegerField()),
            ],
        ),
    ]
