# Generated by Django 3.2.6 on 2021-10-12 16:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0006_testrankings'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
