# Generated by Django 3.2.6 on 2021-10-14 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0008_odiallrounderrankings_odibattingrankings_odibowlingrankings_oditeamrankings_tallrounderrankings_tbat'),
    ]

    operations = [
        migrations.CreateModel(
            name='Teams',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sno', models.IntegerField()),
                ('teams', models.CharField(max_length=80)),
                ('country', models.ImageField(default='default.jpg', upload_to=None)),
            ],
        ),
    ]
