# Generated by Django 3.2.6 on 2021-10-14 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0010_remove_teams_teams'),
    ]

    operations = [
        migrations.AddField(
            model_name='teams',
            name='logo',
            field=models.ImageField(default='default.jpg', upload_to=None),
        ),
        migrations.AlterField(
            model_name='teams',
            name='country',
            field=models.CharField(max_length=80),
        ),
    ]
