# Generated by Django 3.2.6 on 2021-10-14 05:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0011_auto_20211014_1109'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Teams',
            new_name='TeamsImages',
        ),
    ]
