# Generated by Django 3.2.6 on 2021-10-18 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0015_comment_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='name',
            field=models.CharField(max_length=80, null=True),
        ),
    ]
