# Generated by Django 3.2.6 on 2021-10-18 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0016_alter_comment_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teamsimages',
            name='logo',
            field=models.ImageField(default='default', upload_to="{% static 'images/css/' %}"),
        ),
    ]
