# Generated by Django 3.2.6 on 2021-10-19 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0020_alter_teamsimages_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teamsimages',
            name='logo',
            field=models.ImageField(upload_to='uploads/'),
        ),
    ]
